const About = () => (
    <div>
        <h2 style={{ textAlign: 'center' }}>About</h2>
        <p style={{ margin: '10px'}}>
            The Logs Monitor application is a  platform for analysing logs generated by Noisrucer.
        </p>

    </div>
)
export default About;